# Generated by Django 3.1.3 on 2020-11-03 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_first_name', models.CharField(max_length=30)),
                ('customer_last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_email_address', models.EmailField(blank=True, max_length=100, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'New'), (1, 'In progress'), (2, 'Done')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Order',
            },
        ),
    ]
