# Generated by Django 3.1.3 on 2020-11-04 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20201104_1922'),
        ('order', '0002_auto_20201104_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='product.product'),
            preserve_default=False,
        ),
    ]
