# Generated by Django 3.1.3 on 2020-11-04 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20201104_1922'),
        ('order', '0003_ordermodel_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderModel',
            new_name='Order',
        ),
    ]
