# Generated by Django 3.1.3 on 2020-11-03 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20201103_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'New'), (1, 'In progress'), (2, 'Done')], default=0),
        ),
    ]
