# Generated by Django 3.1.3 on 2020-11-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20201104_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_comment',
            field=models.TextField(blank=True, null=True, verbose_name="Customer's comment to the order"),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name="Admin's comment"),
        ),
    ]
